# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sangsoo Nam | Unlimited Power
description: >
  I'm a tech lead who likes learning, discussing, and solving interesting problems.
  These days, I'm focusing on Android development at Spotify
baseurl: "" # the subpath of your site, e.g. /blog
future: false

# Build settings
markdown: kramdown

collections:
  posts_kr:
    output: true
    permalink: /kr/:path:output_ext

paginate: 6
plugins:
  - jekyll-gist
  - jekyll-paginate

sass:
    style: compressed
